"""
[Homework]
1. Rewriting Guessing Number Game
Guessing a number randomly generated by system in the range of 1 to 100
Allowing user to make 8 trials at most
Requirements:
exception handling is required
Program should not get crushed with an input
User may input from keyboard


2. Rewriting Guessing Number Game
Guessing a number randomly generated by system in the range of 1 to 100
Allowing machine (computer) to make 8 trials at most
Requirements:
User-defined exception is required
Program should not get crushed in any case
Game program should execute by itself

solution 1.
binary


solution 2.
random

"""

