print("\n\n")
company = "East Repair Inc."
print("{:<}{:>70}".format(company,"INVOICE"))
print()
address = "1912 Harvest Lane\nNew York, NY 12210"
print("{:<}".format(address))
print()
print()
print()
print()
print("{:<20}{:>12}{:>38}{:>16}".format("Bill To","Ship To","Invoice #", "US-001"))
name = "John Smith"
print("{:<20}{:>15}{:>35}{:>16}".format(name,name,"Invoice Date", "11/02/2019"))
print("{:<20}{:>24}{:>26}{:>16}".format("2 Court Square","3787 Pineview drive","P.Q.#", "2312/2019"))
print("{:<20}{:>24}".format("New York, NY 12210","Cambridge, MA 12210"))
print("{:>70}{:>16}".format("Due Date", "26/02/2019"))
print()
print()
print("______________________________________________________________________________________")
print("|{:^8}|{:^35}|{:^16}|{:^22}|".format("QTY","DESCRIPTION","UNIT PRICE","AMOUNT"))
print("______________________________________________________________________________________")
print("|{:^8}|{:<35}|{:>16}|{:>22}|".format("1","Front and rear brake cables","100.00","100.00"))
print("______________________________________________________________________________________")
print("|{:^8}|{:<35}|{:>16}|{:>22}|".format("2","New set of pedal arms","15.00","30.00"))
print("______________________________________________________________________________________")
print("|{:^8}|{:<35}|{:>16}|{:>22}|".format("3","Labor 3hrs","5.00","15.00"))
print("______________________________________________________________________________________")
print("{:>62}|{:>22}|".format("Subtotal","145.00"))
print("{:>62}|{:>22}|".format("Sales Tax 6.25%","9.06"))
print("                                                               _______________________")
print("{:>62}|{:>22}|".format("TOTAL","$154.06"))
print()
print()
print()
print("{:<}".format("Terms & Conditions"))
print("{:<}".format("Payment is due within 15 days"))
print()
print("{:<}".format("Please make checks payable to: East Repair Inc."))
print("\n\n")