"""
[Homework]
1. Rewriting Guessing Number Game
Guessing a number randomly generated by system in the range of 1 to 100
Allowing user to make 8 trials at most
Requirements:
exception handling is required
Program should not get crushed with an input
User may input from keyboard
"""

import py201107.errors as err

import random

print("Welcome to my guessing number game.")

x = random.randint(1, 100)
i2 = 8

print("Now, please guess a number between 1 and 100.")

for i in range(0, i2):
    num = input("Please input an number: ")

    try:
        num = int(num)

        if num < 1:
            raise err.TooSmallNumberError("Number is too small than 1")

        if num > 100:
            raise err.TooBigNumberError("Number is too big than 100")

    except ValueError as ve:
        print("You must try again. {}".format(ve))
        print()

    except err.TooBigNumberError as ue1:
        print(ue1)
        print()

    except err.TooSmallNumberError as ue2:
        print(ue2)
        print()

    except Exception as e:
        print(e)
        print()

    else:
        if x == num:
            print("Bingo, You find the right answer, it is {}".format(x))
            print("Good buy, have you a nice day!")
            break

        elif num < x:
            print("The number is too small")

        else:
            print("The number is too big")

if num != x:
    print()
    print("Sorry, this you last chance, the right answer is {}".format(x))

print("====== end ======")



